# version: '3.8'

services:
  # Airflow Metadata Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow Scheduler & Webserver
  airflow-webserver:
    # image: apache/airflow:2.9.2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'my_shared_secret_key'
      PYTHONPATH: /opt/airflow
      
    volumes:
      - ./orchestrator/dags:/opt/airflow/dags/orchestrator
      - ./orchestrator/config:/opt/airflow/dags/config
      - ./email_validation/dags:/opt/airflow/dags/email_validation
      - ./email_validation/cpp:/opt/airflow/dags/email_validation/cpp
      - ./email_validation/scripts:/opt/airflow/dags/email_validation/scripts
      - ./reverse_geocode/dags:/opt/airflow/dags/reverse_geocode
      - ./gender_enrichment/dags:/opt/airflow/dags/gender_enrichment
      - ./common/libs:/opt/airflow/common/libs
      - ./samples/input:/samples/input
      - ./samples/output:/samples/output
      - ./tmp:/tmp
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    # image: apache/airflow:2.9.2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: 'my_shared_secret_key'
      PYTHONPATH: /opt/airflow
    volumes:
      - ./orchestrator/dags:/opt/airflow/dags/orchestrator
      - ./orchestrator/config:/opt/airflow/dags/config
      - ./email_validation/dags:/opt/airflow/dags/email_validation
      - ./email_validation/cpp:/opt/airflow/dags/email_validation/cpp
      - ./email_validation/scripts:/opt/airflow/dags/email_validation/scripts
      - ./reverse_geocode/dags:/opt/airflow/dags/reverse_geocode
      - ./gender_enrichment/dags:/opt/airflow/dags/gender_enrichment
      - ./common/libs:/opt/airflow/common/libs
      - ./samples/input:/samples/input
      - ./samples/output:/samples/output
      - ./tmp:/tmp
    command: scheduler

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Kafka + Zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

volumes:
  postgres_data:
  minio_data:
