if(EXISTS "/workspace/build-linux/email_validation/cpp/tests/runTests[1]_tests.cmake")
  include("/workspace/build-linux/email_validation/cpp/tests/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
