main_input_topic: "enrich-input-topic"
main_out_topic: "enrich-output-topic"
mode: "stream"

sequence:
  - dag_id: email_validation
    mode: "stream"
    input_topic: "enrich-input-topic"
    out_topic: "email-validation-output-topic"

  - dag_id: reverse_geocode
    mode: "stream"
    input_topic: "email-validation-output-topic"
    out_topic: "reverse-geocode-output-topic"

  - dag_id: gender_enrichment
    mode: "stream"
    input_topic: "reverse-geocode-output-topic"
    out_topic: "enrich-output-topic"